use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

pub const CURRENT_SCHEMA_VERSION: u32 = 2;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuerySpec {
    pub tables: Vec<TableRef>,
    pub columns: Vec<ColumnSel>,
    pub joins: Vec<JoinSpec>,
    pub filters: FilterGroup,
    pub limit: u32,
    #[serde(default = "default_schema_version")]
    pub schema_version: u32,
    /// Per-child connector overrides keyed by the child's `id`. When an
    /// entry is present, the override is used to join that child with its
    /// previous sibling instead of the parent group's `connector`. Absent
    /// or unknown IDs fall back to the parent group's connector. IDs are
    /// stable across sibling mutations, so removing or inserting siblings
    /// does not silently rebind an override to a different child.
    #[serde(default)]
    pub connector_overrides: BTreeMap<String, GroupConnector>,
}

fn default_schema_version() -> u32 {
    CURRENT_SCHEMA_VERSION
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TableRef {
    pub schema: String,
    pub name: String,
    pub alias: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ColumnSel {
    pub table_alias: String,
    pub column: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JoinSpec {
    pub left_alias: String,
    pub left_column: String,
    pub right_alias: String,
    pub right_column: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum FilterNode {
    Leaf(FilterSpec),
    Group(FilterGroup),
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FilterGroup {
    /// Stable identifier used to key `connector_overrides`. Generated by the
    /// frontend on node creation; absent IDs default to an empty string so
    /// legacy specs without IDs still deserialize.
    #[serde(default)]
    pub id: String,
    pub connector: GroupConnector,
    pub children: Vec<FilterNode>,
}

impl Default for FilterGroup {
    fn default() -> Self {
        FilterGroup {
            id: String::new(),
            connector: GroupConnector::And,
            children: Vec::new(),
        }
    }
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub enum GroupConnector {
    And,
    Or,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FilterSpec {
    /// Stable identifier used to key `connector_overrides`. Generated by the
    /// frontend on node creation; absent IDs default to an empty string so
    /// legacy specs without IDs still deserialize.
    #[serde(default)]
    pub id: String,
    pub table_alias: String,
    pub column: String,
    pub op: FilterOp,
    pub value: Option<FilterValue>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum FilterValue {
    Single(FilterLiteral),
    List(Vec<FilterLiteral>),
    Pair(FilterLiteral, FilterLiteral),
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FilterLiteral {
    pub kind: LiteralKind,
    pub text: String,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub enum LiteralKind {
    Text,
    Int,
    Float,
    Bool,
    Date,
    DateTime,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub enum FilterOp {
    Eq,
    Ne,
    Gt,
    Gte,
    Lt,
    Lte,
    Like,
    NotLike,
    Ilike,
    In,
    NotIn,
    Between,
    IsNull,
    IsNotNull,
    IsEmpty,
    IsNotEmpty,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ValueKind {
    None,
    Single,
    List,
    Pair,
}

impl FilterOp {
    pub fn value_kind(&self) -> ValueKind {
        match self {
            FilterOp::IsNull | FilterOp::IsNotNull | FilterOp::IsEmpty | FilterOp::IsNotEmpty => {
                ValueKind::None
            }
            FilterOp::In | FilterOp::NotIn => ValueKind::List,
            FilterOp::Between => ValueKind::Pair,
            _ => ValueKind::Single,
        }
    }

    pub fn needs_value(&self) -> bool {
        self.value_kind() != ValueKind::None
    }

    pub fn sql_operator(&self) -> Option<&'static str> {
        match self {
            FilterOp::Eq => Some("="),
            FilterOp::Ne => Some("<>"),
            FilterOp::Gt => Some(">"),
            FilterOp::Gte => Some(">="),
            FilterOp::Lt => Some("<"),
            FilterOp::Lte => Some("<="),
            FilterOp::Like => Some("LIKE"),
            FilterOp::NotLike => Some("NOT LIKE"),
            _ => None,
        }
    }
}

#[derive(Debug, Clone)]
pub enum BindValue {
    Text(String),
    Int(i64),
    Float(f64),
    Bool(bool),
    Null,
}

impl BindValue {
    pub fn from_literal(lit: &FilterLiteral) -> Result<Self, String> {
        match lit.kind {
            LiteralKind::Text => Ok(BindValue::Text(lit.text.clone())),
            LiteralKind::Int => lit
                .text
                .parse::<i64>()
                .map(BindValue::Int)
                .map_err(|_| format!("'{}' is not a valid integer", lit.text)),
            LiteralKind::Float => lit
                .text
                .parse::<f64>()
                .map(BindValue::Float)
                .map_err(|_| format!("'{}' is not a valid number", lit.text)),
            LiteralKind::Bool => lit
                .text
                .parse::<bool>()
                .or_else(|_| {
                    if lit.text.eq_ignore_ascii_case("true")
                        || lit.text.eq_ignore_ascii_case("1")
                        || lit.text.eq_ignore_ascii_case("yes")
                    {
                        Ok(true)
                    } else if lit.text.eq_ignore_ascii_case("false")
                        || lit.text.eq_ignore_ascii_case("0")
                        || lit.text.eq_ignore_ascii_case("no")
                        || lit.text.is_empty()
                    {
                        Ok(false)
                    } else {
                        Err(())
                    }
                })
                .map(BindValue::Bool)
                .map_err(|_| format!("'{}' is not a valid boolean", lit.text)),
            LiteralKind::Date | LiteralKind::DateTime => Ok(BindValue::Text(lit.text.clone())),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QueryResult {
    pub columns: Vec<String>,
    pub rows: Vec<Vec<serde_json::Value>>,
    pub row_count: usize,
    pub truncated: bool,
    pub warnings: Vec<String>,
}

#[derive(Debug, Clone)]
pub struct CompiledQuery {
    pub sql: String,
    pub params: Vec<BindValue>,
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeMap;

    #[test]
    fn filter_op_value_kind_table() {
        assert_eq!(FilterOp::Eq.value_kind(), ValueKind::Single);
        assert_eq!(FilterOp::Ne.value_kind(), ValueKind::Single);
        assert_eq!(FilterOp::Gt.value_kind(), ValueKind::Single);
        assert_eq!(FilterOp::Gte.value_kind(), ValueKind::Single);
        assert_eq!(FilterOp::Lt.value_kind(), ValueKind::Single);
        assert_eq!(FilterOp::Lte.value_kind(), ValueKind::Single);
        assert_eq!(FilterOp::Like.value_kind(), ValueKind::Single);
        assert_eq!(FilterOp::NotLike.value_kind(), ValueKind::Single);
        assert_eq!(FilterOp::Ilike.value_kind(), ValueKind::Single);
        assert_eq!(FilterOp::In.value_kind(), ValueKind::List);
        assert_eq!(FilterOp::NotIn.value_kind(), ValueKind::List);
        assert_eq!(FilterOp::Between.value_kind(), ValueKind::Pair);
        assert_eq!(FilterOp::IsNull.value_kind(), ValueKind::None);
        assert_eq!(FilterOp::IsNotNull.value_kind(), ValueKind::None);
        assert_eq!(FilterOp::IsEmpty.value_kind(), ValueKind::None);
        assert_eq!(FilterOp::IsNotEmpty.value_kind(), ValueKind::None);
    }

    #[test]
    fn needs_value_is_inverse_of_value_kind_none() {
        assert!(!FilterOp::IsNull.needs_value());
        assert!(!FilterOp::IsNotNull.needs_value());
        assert!(!FilterOp::IsEmpty.needs_value());
        assert!(!FilterOp::IsNotEmpty.needs_value());
        assert!(FilterOp::Eq.needs_value());
        assert!(FilterOp::Between.needs_value());
        assert!(FilterOp::In.needs_value());
    }

    #[test]
    fn sql_operator_for_comparison_and_like_ops() {
        assert_eq!(FilterOp::Eq.sql_operator(), Some("="));
        assert_eq!(FilterOp::Ne.sql_operator(), Some("<>"));
        assert_eq!(FilterOp::Gt.sql_operator(), Some(">"));
        assert_eq!(FilterOp::Gte.sql_operator(), Some(">="));
        assert_eq!(FilterOp::Lt.sql_operator(), Some("<"));
        assert_eq!(FilterOp::Lte.sql_operator(), Some("<="));
        assert_eq!(FilterOp::Like.sql_operator(), Some("LIKE"));
        assert_eq!(FilterOp::NotLike.sql_operator(), Some("NOT LIKE"));
        assert_eq!(FilterOp::Ilike.sql_operator(), None);
        assert_eq!(FilterOp::In.sql_operator(), None);
        assert_eq!(FilterOp::Between.sql_operator(), None);
        assert_eq!(FilterOp::IsNull.sql_operator(), None);
    }

    #[test]
    fn bind_value_from_literal_text() {
        let lit = FilterLiteral {
            kind: LiteralKind::Text,
            text: "Alice".to_string(),
        };
        match BindValue::from_literal(&lit).unwrap() {
            BindValue::Text(s) => assert_eq!(s, "Alice"),
            other => panic!("expected Text, got {other:?}"),
        }
    }

    #[test]
    fn bind_value_from_literal_int_ok_and_err() {
        let ok = FilterLiteral {
            kind: LiteralKind::Int,
            text: "42".to_string(),
        };
        match BindValue::from_literal(&ok).unwrap() {
            BindValue::Int(n) => assert_eq!(n, 42),
            other => panic!("expected Int, got {other:?}"),
        }
        let bad = FilterLiteral {
            kind: LiteralKind::Int,
            text: "not a number".to_string(),
        };
        let err = BindValue::from_literal(&bad).unwrap_err();
        assert!(err.contains("not a valid integer"), "got: {err}");
    }

    #[test]
    fn bind_value_from_literal_float_ok_and_err() {
        let ok = FilterLiteral {
            kind: LiteralKind::Float,
            text: "1.5".to_string(),
        };
        match BindValue::from_literal(&ok).unwrap() {
            BindValue::Float(f) => assert!((f - 1.5).abs() < 1e-9),
            other => panic!("expected Float, got {other:?}"),
        }
        let bad = FilterLiteral {
            kind: LiteralKind::Float,
            text: "abc".to_string(),
        };
        let err = BindValue::from_literal(&bad).unwrap_err();
        assert!(err.contains("not a valid number"), "got: {err}");
    }

    #[test]
    fn bind_value_from_literal_bool_accepts_canonical_and_aliases() {
        for text in ["true", "TRUE", "True", "1", "yes", "YES"] {
            let lit = FilterLiteral {
                kind: LiteralKind::Bool,
                text: text.to_string(),
            };
            assert!(matches!(
                BindValue::from_literal(&lit).unwrap(),
                BindValue::Bool(true)
            ));
        }
        for text in ["false", "FALSE", "False", "0", "no", "NO", ""] {
            let lit = FilterLiteral {
                kind: LiteralKind::Bool,
                text: text.to_string(),
            };
            assert!(matches!(
                BindValue::from_literal(&lit).unwrap(),
                BindValue::Bool(false)
            ));
        }
        let bad = FilterLiteral {
            kind: LiteralKind::Bool,
            text: "maybe".to_string(),
        };
        let err = BindValue::from_literal(&bad).unwrap_err();
        assert!(err.contains("not a valid boolean"), "got: {err}");
    }

    #[test]
    fn bind_value_from_literal_date_and_datetime_become_text() {
        let d = FilterLiteral {
            kind: LiteralKind::Date,
            text: "2025-01-02".to_string(),
        };
        match BindValue::from_literal(&d).unwrap() {
            BindValue::Text(s) => assert_eq!(s, "2025-01-02"),
            other => panic!("expected Text, got {other:?}"),
        }
        let dt = FilterLiteral {
            kind: LiteralKind::DateTime,
            text: "2025-01-02T03:04:05Z".to_string(),
        };
        match BindValue::from_literal(&dt).unwrap() {
            BindValue::Text(s) => assert_eq!(s, "2025-01-02T03:04:05Z"),
            other => panic!("expected Text, got {other:?}"),
        }
    }

    #[test]
    fn filter_group_default_is_empty_and_group_with_id() {
        let g = FilterGroup::default();
        assert_eq!(g.id, "");
        assert_eq!(g.connector, GroupConnector::And);
        assert!(g.children.is_empty());
    }

    #[test]
    fn query_spec_round_trip_with_connector_overrides() {
        let spec = QuerySpec {
            tables: vec![TableRef {
                schema: "public".into(),
                name: "users".into(),
                alias: "t0".into(),
            }],
            columns: vec![ColumnSel {
                table_alias: "t0".into(),
                column: "id".into(),
            }],
            joins: vec![],
            filters: FilterGroup {
                id: "root".into(),
                connector: GroupConnector::And,
                children: vec![],
            },
            limit: 50,
            schema_version: CURRENT_SCHEMA_VERSION,
            connector_overrides: BTreeMap::from([("leaf-1".to_string(), GroupConnector::Or)]),
        };
        let json = serde_json::to_string(&spec).unwrap();
        let back: QuerySpec = serde_json::from_str(&json).unwrap();
        assert_eq!(back.limit, 50);
        assert_eq!(back.schema_version, CURRENT_SCHEMA_VERSION);
        assert_eq!(
            back.connector_overrides.get("leaf-1"),
            Some(&GroupConnector::Or)
        );
        assert_eq!(back.tables[0].alias, "t0");
    }

    #[test]
    fn query_spec_deserializes_legacy_spec_without_connector_overrides_or_id() {
        // A legacy payload (no schema_version override, no id, no
        // connector_overrides) should still deserialize thanks to the
        // #[serde(default)] attributes on the relevant fields.
        let json = r#"{
            "tables": [],
            "columns": [],
            "joins": [],
            "filters": { "connector": "And", "children": [] },
            "limit": 100
        }"#;
        let spec: QuerySpec = serde_json::from_str(json).unwrap();
        assert_eq!(spec.schema_version, CURRENT_SCHEMA_VERSION);
        assert!(spec.connector_overrides.is_empty());
        assert_eq!(spec.filters.id, "");
    }
}
