use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

pub const CURRENT_SCHEMA_VERSION: u32 = 3;
pub const MAX_CELL_BYTES: usize = 1024 * 1024;
pub const MAX_RESULT_BYTES: usize = 10 * 1024 * 1024;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuerySpec {
    pub tables: Vec<TableRef>,
    pub columns: Vec<ColumnSel>,
    pub joins: Vec<JoinSpec>,
    pub filters: FilterGroup,
    pub limit: u32,
    #[serde(default = "default_schema_version")]
    pub schema_version: u32,
    /// Per-child connector overrides keyed by the child's `id`. When an
    /// entry is present, the override is used to join that child with its
    /// previous sibling instead of the parent group's `connector`. Absent
    /// or unknown IDs fall back to the parent group's connector. IDs are
    /// stable across sibling mutations, so removing or inserting siblings
    /// does not silently rebind an override to a different child.
    #[serde(default)]
    pub connector_overrides: BTreeMap<String, GroupConnector>,
}

fn default_schema_version() -> u32 {
    CURRENT_SCHEMA_VERSION
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TableRef {
    pub schema: String,
    pub name: String,
    pub alias: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ColumnSel {
    pub table_alias: String,
    pub column: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JoinSpec {
    pub left_alias: String,
    pub left_column: String,
    pub right_alias: String,
    pub right_column: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum FilterNode {
    Leaf(FilterSpec),
    Group(FilterGroup),
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FilterGroup {
    /// Stable identifier used to key `connector_overrides`. Generated by the
    /// frontend on node creation; absent IDs default to an empty string so
    /// legacy specs without IDs still deserialize.
    #[serde(default)]
    pub id: String,
    pub connector: GroupConnector,
    pub children: Vec<FilterNode>,
}

impl Default for FilterGroup {
    fn default() -> Self {
        FilterGroup {
            id: uuid::Uuid::new_v4().to_string(),
            connector: GroupConnector::And,
            children: Vec::new(),
        }
    }
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub enum GroupConnector {
    And,
    Or,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FilterSpec {
    /// Stable identifier used to key `connector_overrides`. Generated by the
    /// frontend on node creation; absent IDs default to an empty string so
    /// legacy specs without IDs still deserialize.
    #[serde(default)]
    pub id: String,
    pub table_alias: String,
    pub column: String,
    pub op: FilterOp,
    pub value: Option<FilterValue>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum FilterValue {
    Single(FilterLiteral),
    List(Vec<FilterLiteral>),
    Pair(FilterLiteral, FilterLiteral),
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FilterLiteral {
    pub kind: LiteralKind,
    pub text: String,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub enum LiteralKind {
    Text,
    Int,
    Decimal,
    Float,
    Bool,
    Date,
    DateTime,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub enum FilterOp {
    Eq,
    Ne,
    Gt,
    Gte,
    Lt,
    Lte,
    Like,
    NotLike,
    Ilike,
    In,
    NotIn,
    Between,
    IsNull,
    IsNotNull,
    IsEmpty,
    IsNotEmpty,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ValueKind {
    None,
    Single,
    List,
    Pair,
}

impl FilterOp {
    pub fn value_kind(&self) -> ValueKind {
        match self {
            FilterOp::IsNull | FilterOp::IsNotNull | FilterOp::IsEmpty | FilterOp::IsNotEmpty => {
                ValueKind::None
            }
            FilterOp::In | FilterOp::NotIn => ValueKind::List,
            FilterOp::Between => ValueKind::Pair,
            _ => ValueKind::Single,
        }
    }

    pub fn needs_value(&self) -> bool {
        self.value_kind() != ValueKind::None
    }

    pub fn sql_operator(&self) -> Option<&'static str> {
        match self {
            FilterOp::Eq => Some("="),
            FilterOp::Ne => Some("<>"),
            FilterOp::Gt => Some(">"),
            FilterOp::Gte => Some(">="),
            FilterOp::Lt => Some("<"),
            FilterOp::Lte => Some("<="),
            FilterOp::Like => Some("LIKE"),
            FilterOp::NotLike => Some("NOT LIKE"),
            _ => None,
        }
    }
}

#[derive(Debug, Clone)]
pub enum BindValue {
    Text(String),
    Int(i64),
    Decimal(bigdecimal::BigDecimal),
    Float(f64),
    Bool(bool),
    Date(chrono::NaiveDate),
    DateTime(chrono::NaiveDateTime),
    Null,
}

impl BindValue {
    pub fn from_literal(lit: &FilterLiteral) -> Result<Self, String> {
        match lit.kind {
            LiteralKind::Text => Ok(BindValue::Text(lit.text.clone())),
            LiteralKind::Int => lit
                .text
                .parse::<i64>()
                .map(BindValue::Int)
                .map_err(|_| format!("'{}' is not a valid integer", lit.text)),
            LiteralKind::Decimal => lit
                .text
                .parse::<bigdecimal::BigDecimal>()
                .map(BindValue::Decimal)
                .map_err(|_| format!("'{}' is not a valid decimal", lit.text)),
            LiteralKind::Float => lit
                .text
                .parse::<f64>()
                .map(BindValue::Float)
                .map_err(|_| format!("'{}' is not a valid number", lit.text)),
            LiteralKind::Bool => lit
                .text
                .parse::<bool>()
                .or_else(|_| {
                    if lit.text.eq_ignore_ascii_case("true")
                        || lit.text.eq_ignore_ascii_case("1")
                        || lit.text.eq_ignore_ascii_case("yes")
                    {
                        Ok(true)
                    } else if lit.text.eq_ignore_ascii_case("false")
                        || lit.text.eq_ignore_ascii_case("0")
                        || lit.text.eq_ignore_ascii_case("no")
                        || lit.text.is_empty()
                    {
                        Ok(false)
                    } else {
                        Err(())
                    }
                })
                .map(BindValue::Bool)
                .map_err(|_| format!("'{}' is not a valid boolean", lit.text)),
            LiteralKind::Date => parse_date_literal(&lit.text).map(BindValue::Date),
            LiteralKind::DateTime => parse_datetime_literal(&lit.text).map(BindValue::DateTime),
        }
    }
}

pub fn parse_date_literal(text: &str) -> Result<chrono::NaiveDate, String> {
    chrono::NaiveDate::parse_from_str(text.trim(), "%Y-%m-%d")
        .map_err(|_| format!("'{text}' is not a valid date; expected YYYY-MM-DD"))
}

pub fn parse_datetime_literal(text: &str) -> Result<chrono::NaiveDateTime, String> {
    let trimmed = text.trim();
    chrono::NaiveDateTime::parse_from_str(trimmed, "%Y-%m-%dT%H:%M:%S%.f")
        .or_else(|_| chrono::NaiveDateTime::parse_from_str(trimmed, "%Y-%m-%dT%H:%M"))
        .or_else(|_| chrono::NaiveDateTime::parse_from_str(trimmed, "%Y-%m-%d %H:%M:%S%.f"))
        .or_else(|_| chrono::DateTime::parse_from_rfc3339(trimmed).map(|dt| dt.naive_utc()))
        .map_err(|_| {
            format!("'{text}' is not a valid datetime; expected YYYY-MM-DDTHH:MM[:SS] or RFC3339")
        })
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QueryResult {
    pub columns: Vec<ResultColumn>,
    pub rows: Vec<Vec<ResultCell>>,
    pub row_count: usize,
    pub truncated: bool,
    pub warnings: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct ResultColumn {
    pub name: String,
    pub data_type: String,
}

impl ResultColumn {
    pub fn new(name: impl Into<String>, data_type: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            data_type: data_type.into(),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "kind", content = "value")]
pub enum ResultCell {
    Null,
    Bool(bool),
    Integer(i64),
    Float(f64),
    Text { text: String, truncated: bool },
    Binary { base64: String, truncated: bool },
}

impl ResultCell {
    pub fn text(value: impl Into<String>) -> Self {
        let mut text = value.into();
        let truncated = text.len() > MAX_CELL_BYTES;
        if truncated {
            let mut boundary = MAX_CELL_BYTES;
            while !text.is_char_boundary(boundary) {
                boundary -= 1;
            }
            text.truncate(boundary);
        }
        Self::Text { text, truncated }
    }

    pub fn binary(value: &[u8]) -> Self {
        use base64::Engine;
        let truncated = value.len() > MAX_CELL_BYTES;
        let value = &value[..value.len().min(MAX_CELL_BYTES)];
        Self::Binary {
            base64: base64::engine::general_purpose::STANDARD.encode(value),
            truncated,
        }
    }

    fn was_truncated(&self) -> bool {
        matches!(
            self,
            ResultCell::Text {
                truncated: true,
                ..
            } | ResultCell::Binary {
                truncated: true,
                ..
            }
        )
    }
}

impl QueryResult {
    pub fn from_rows(columns: Vec<ResultColumn>, rows: Vec<Vec<ResultCell>>) -> Self {
        let mut kept = Vec::with_capacity(rows.len());
        let mut encoded_bytes = 0usize;
        let mut result_truncated = false;
        let mut cell_truncated = false;

        for row in rows {
            cell_truncated |= row.iter().any(ResultCell::was_truncated);
            let row_bytes = serde_json::to_vec(&row).map_or(MAX_RESULT_BYTES + 1, |v| v.len());
            if encoded_bytes.saturating_add(row_bytes) > MAX_RESULT_BYTES {
                result_truncated = true;
                break;
            }
            encoded_bytes += row_bytes;
            kept.push(row);
        }

        let mut warnings = Vec::new();
        if cell_truncated {
            warnings.push(format!(
                "One or more cells exceeded {} bytes and were truncated",
                MAX_CELL_BYTES
            ));
        }
        if result_truncated {
            warnings.push(format!(
                "Result exceeded {} encoded bytes and was truncated",
                MAX_RESULT_BYTES
            ));
        }

        Self {
            row_count: kept.len(),
            columns,
            rows: kept,
            truncated: result_truncated,
            warnings,
        }
    }
}

#[derive(Debug, Clone)]
pub struct CompiledQuery {
    pub sql: String,
    pub params: Vec<BindValue>,
}
