package com.safedb.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color
import com.safedb.model.ThemePalette

@Immutable
internal data class ThemePaletteSpec(
    val background: Color,
    val surface: Color,
    val containerLowest: Color,
    val containerLow: Color,
    val container: Color,
    val containerHigh: Color,
    val containerHighest: Color,
    val outline: Color,
    val outlineVariant: Color,
    val onSurface: Color,
    val onSurfaceVariant: Color,
    val accent: Color,
    val onAccent: Color,
    val accentHover: Color,
    val accentContainer: Color,
    val onAccentContainer: Color,
    val workspaceBackground: Color,
    val workspaceHeader: Color,
    val workspacePanel: Color,
    val workspaceCanvas: Color,
    val navigationBackground: Color,
    val navigationBorder: Color,
    val navigationHover: Color,
    val navigationSelected: Color,
    val onNavigation: Color,
    val onNavigationMuted: Color,
    val success: Color,
    val onSuccess: Color,
    val successContainer: Color,
    val onSuccessContainer: Color,
    val warning: Color,
    val onWarning: Color,
    val warningContainer: Color,
    val onWarningContainer: Color,
    val info: Color,
    val onInfo: Color,
    val infoContainer: Color,
    val onInfoContainer: Color,
    val uq: Color,
    val onUq: Color,
    val uqContainer: Color,
    val onUqContainer: Color,
    val error: Color,
    val onError: Color,
    val errorContainer: Color,
    val onErrorContainer: Color,
    val scrim: Color,
    val series: List<Color>,
    // Material's primary slots follow the accent unless a palette needs different ones; Control
    // Blue
    // keeps a lighter dark primary so tinted icons stay readable.
    val materialPrimary: Color = accent,
    val onMaterialPrimary: Color = onAccent,
    val materialPrimaryContainer: Color = accentContainer,
    val onMaterialPrimaryContainer: Color = onAccentContainer,
)

internal fun ThemePaletteSpec.toScheme(isDark: Boolean): Pair<ColorScheme, SafeDbColors> {
    val base = if (isDark) darkColorScheme() else lightColorScheme()
    return base.copy(
        primary = materialPrimary,
        onPrimary = onMaterialPrimary,
        primaryContainer = materialPrimaryContainer,
        onPrimaryContainer = onMaterialPrimaryContainer,
        inversePrimary = accentHover,
        secondary = info,
        onSecondary = onInfo,
        secondaryContainer = infoContainer,
        onSecondaryContainer = onInfoContainer,
        tertiary = warning,
        onTertiary = onWarning,
        tertiaryContainer = warningContainer,
        onTertiaryContainer = onWarningContainer,
        background = background,
        onBackground = onSurface,
        surface = surface,
        onSurface = onSurface,
        surfaceVariant = container,
        onSurfaceVariant = onSurfaceVariant,
        surfaceTint = materialPrimary,
        inverseSurface = onSurface,
        inverseOnSurface = background,
        error = error,
        onError = onError,
        errorContainer = errorContainer,
        onErrorContainer = onErrorContainer,
        outline = outline,
        outlineVariant = outlineVariant,
        scrim = scrim,
        surfaceContainerLowest = containerLowest,
        surfaceContainerLow = containerLow,
        surfaceContainer = container,
        surfaceContainerHigh = containerHigh,
        surfaceContainerHighest = containerHighest,
    ) to
        SafeDbColors(
            actionPrimary = accent,
            onActionPrimary = onAccent,
            actionPrimaryHover = accentHover,
            accentContainer = accentContainer,
            onAccentContainer = onAccentContainer,
            workspaceBackground = workspaceBackground,
            workspaceHeader = workspaceHeader,
            workspacePanel = workspacePanel,
            workspaceCanvas = workspaceCanvas,
            navigationBackground = navigationBackground,
            navigationBorder = navigationBorder,
            navigationHover = navigationHover,
            navigationSelected = navigationSelected,
            onNavigation = onNavigation,
            onNavigationMuted = onNavigationMuted,
            success = success,
            onSuccess = onSuccess,
            successContainer = successContainer,
            onSuccessContainer = onSuccessContainer,
            warning = warning,
            onWarning = onWarning,
            warningContainer = warningContainer,
            onWarningContainer = onWarningContainer,
            info = info,
            onInfo = onInfo,
            infoContainer = infoContainer,
            onInfoContainer = onInfoContainer,
            uq = uq,
            onUq = onUq,
            uqContainer = uqContainer,
            onUqContainer = onUqContainer,
            series = series,
        )
}

internal fun paletteSpecFor(palette: ThemePalette, isDark: Boolean): ThemePaletteSpec =
    when (palette) {
        ThemePalette.ControlBlue -> if (isDark) ControlBlueDark else ControlBlueLight
        ThemePalette.SignalTeal -> if (isDark) SignalTealDark else SignalTealLight
        ThemePalette.Oxide -> if (isDark) OxideDark else OxideLight
        ThemePalette.CommandViolet -> if (isDark) CommandVioletDark else CommandVioletLight
    }

private val ControlBlueLight =
    ThemePaletteSpec(
        background = Color(0xFFF7F9FB),
        surface = Color.White,
        containerLowest = Color.White,
        containerLow = Color(0xFFF4F7FA),
        container = Color(0xFFEDF1F5),
        containerHigh = Color(0xFFE5EBF0),
        containerHighest = Color(0xFFDCE4EB),
        outline = Color(0xFFB8C3CE),
        outlineVariant = Color(0xFFD7DFE7),
        onSurface = Color(0xFF17212B),
        onSurfaceVariant = Color(0xFF607080),
        accent = Color(0xFF0B5ED7),
        onAccent = Color.White,
        accentHover = Color(0xFF084CB3),
        accentContainer = Color(0xFFE8F0FF),
        onAccentContainer = Color(0xFF0847A6),
        workspaceBackground = Color(0xFFE6EBF0),
        workspaceHeader = Color(0xFFDCE3E9),
        workspacePanel = Color(0xFFE6EBF0),
        workspaceCanvas = Color(0xFFF7F9FB),
        navigationBackground = Color(0xFF18222D),
        navigationBorder = Color(0xFF344250),
        navigationHover = Color(0xFF222F3C),
        navigationSelected = Color(0xFF202D3A),
        onNavigation = Color(0xFFEAF0F5),
        onNavigationMuted = Color(0xFFA2B1C0),
        success = Color(0xFF047857),
        onSuccess = Color.White,
        successContainer = Color(0xFFECFDF5),
        onSuccessContainer = Color(0xFF047857),
        warning = Color(0xFFB45309),
        onWarning = Color.White,
        warningContainer = Color(0xFFFFFBEB),
        onWarningContainer = Color(0xFF92400E),
        info = Color(0xFF475569),
        onInfo = Color.White,
        infoContainer = Color(0xFFF1F5F9),
        onInfoContainer = Color(0xFF334155),
        uq = Color(0xFF7C3AED),
        onUq = Color.White,
        uqContainer = Color(0xFFF5F3FF),
        onUqContainer = Color(0xFF5B21B6),
        error = Color(0xFFDC2626),
        onError = Color.White,
        errorContainer = Color(0xFFFEF2F2),
        onErrorContainer = Color(0xFFB91C1C),
        scrim = Color(0x66000000),
        series = VisualizationSeriesPalette,
    )

private val ControlBlueDark =
    ThemePaletteSpec(
        background = Color(0xFF0D141C),
        surface = Color(0xFF121B25),
        containerLowest = Color(0xFF0A1118),
        containerLow = Color(0xFF16212C),
        container = Color(0xFF1B2733),
        containerHigh = Color(0xFF22303E),
        containerHighest = Color(0xFF2A3948),
        outline = Color(0xFF3A4958),
        outlineVariant = Color(0xFF2A3846),
        onSurface = Color(0xFFE8EEF4),
        onSurfaceVariant = Color(0xFF97A8B8),
        accent = Color(0xFF4C8DFF),
        onAccent = Color.White,
        accentHover = Color(0xFF72A5FF),
        accentContainer = Color(0xFF18365D),
        onAccentContainer = Color(0xFFB8D0FF),
        workspaceBackground = Color(0xFF16212C),
        workspaceHeader = Color(0xFF1B2733),
        workspacePanel = Color(0xFF16212C),
        workspaceCanvas = Color(0xFF0D141C),
        navigationBackground = Color(0xFF0A1118),
        navigationBorder = Color(0xFF2D3A47),
        navigationHover = Color(0xFF141F29),
        navigationSelected = Color(0xFF172430),
        onNavigation = Color(0xFFE8EEF4),
        onNavigationMuted = Color(0xFF91A3B3),
        success = Color(0xFF34D399),
        onSuccess = Color(0xFF0B1120),
        successContainer = Color(0xFF0A2818),
        onSuccessContainer = Color(0xFF6EE7B7),
        warning = Color(0xFFFCD34D),
        onWarning = Color(0xFF0B1120),
        warningContainer = Color(0xFF2A1F0A),
        onWarningContainer = Color(0xFFFDE68A),
        info = Color(0xFFCBD5E1),
        onInfo = Color(0xFF0B1120),
        infoContainer = Color(0xFF1B2436),
        onInfoContainer = Color(0xFFCBD5E1),
        uq = Color(0xFFC4B5FD),
        onUq = Color(0xFF0B1120),
        uqContainer = Color(0xFF221840),
        onUqContainer = Color(0xFFC4B5FD),
        error = Color(0xFFF87171),
        onError = Color(0xFF0B1120),
        errorContainer = Color(0xFF2A1414),
        onErrorContainer = Color(0xFFFCA5A5),
        scrim = Color(0x99000000),
        // Hue order mirrors VisualizationSeriesPalette so each series keeps its identity
        // when the user toggles between light and dark.
        series =
            listOf(
                Color(0xFF6EA2FF),
                Color(0xFF2DD4BF),
                Color(0xFFFBBF24),
                Color(0xFFA78BFA),
                Color(0xFFFB7185),
                Color(0xFF38BDF8),
                Color(0xFFA3E635),
                Color(0xFFFB923C),
            ),
        materialPrimary = Color(0xFF6EA2FF),
        onMaterialPrimary = Color(0xFF07172C),
        materialPrimaryContainer = Color(0xFF173761),
        onMaterialPrimaryContainer = Color(0xFFB9D1FF),
    )

private val SignalTealLight =
    ThemePaletteSpec(
        background = Color(0xFFF3F7FA),
        surface = Color(0xFFFBFDFE),
        containerLowest = Color(0xFFFFFFFF),
        containerLow = Color(0xFFF3F7FA),
        container = Color(0xFFE7EDF3),
        containerHigh = Color(0xFFDCE5EE),
        containerHighest = Color(0xFFCDDAE6),
        outline = Color(0xFFA3B6C9),
        outlineVariant = Color(0xFFD3DEE8),
        onSurface = Color(0xFF0B2138),
        onSurfaceVariant = Color(0xFF4C6478),
        accent = Color(0xFF0E7490),
        onAccent = Color(0xFFFFFFFF),
        accentHover = Color(0xFF155E75),
        accentContainer = Color(0xFFD6EDF5),
        onAccentContainer = Color(0xFF0B4F63),
        workspaceBackground = Color(0xFFE2EAF0),
        workspaceHeader = Color(0xFFD7E2EB),
        workspacePanel = Color(0xFFE2EAF0),
        workspaceCanvas = Color(0xFFF7FAFC),
        navigationBackground = Color(0xFF102438),
        navigationBorder = Color(0xFF2D4A62),
        navigationHover = Color(0xFF173148),
        navigationSelected = Color(0xFF15384A),
        onNavigation = Color(0xFFE4F0F7),
        onNavigationMuted = Color(0xFF99B0C2),
        success = Color(0xFF047857),
        onSuccess = Color.White,
        successContainer = Color(0xFFDCF2EA),
        onSuccessContainer = Color(0xFF065F46),
        warning = Color(0xFF9A6700),
        onWarning = Color.White,
        warningContainer = Color(0xFFF7EEDA),
        onWarningContainer = Color(0xFF7A5200),
        info = Color(0xFF35566E),
        onInfo = Color.White,
        infoContainer = Color(0xFFE1E9F1),
        onInfoContainer = Color(0xFF25445C),
        uq = Color(0xFF6D28D9),
        onUq = Color.White,
        uqContainer = Color(0xFFE7E3F8),
        onUqContainer = Color(0xFF4C1D95),
        error = Color(0xFFBE123C),
        onError = Color.White,
        errorContainer = Color(0xFFFAE3E9),
        onErrorContainer = Color(0xFF9F1239),
        scrim = Color(0x730B2138),
        series =
            listOf(
                Color(0xFF0E7490),
                Color(0xFF1D4ED8),
                Color(0xFF6D28D9),
                Color(0xFF0F766E),
                Color(0xFF9A6700),
                Color(0xFFBE123C),
                Color(0xFF4D7C0F),
                Color(0xFF35566E),
            ),
    )

private val SignalTealDark =
    ThemePaletteSpec(
        background = Color(0xFF061424),
        surface = Color(0xFF0B1F33),
        containerLowest = Color(0xFF04101C),
        containerLow = Color(0xFF08192A),
        container = Color(0xFF10293F),
        containerHigh = Color(0xFF17334C),
        containerHighest = Color(0xFF1F4160),
        outline = Color(0xFF2A5478),
        outlineVariant = Color(0xFF163149),
        onSurface = Color(0xFFDCEAF6),
        onSurfaceVariant = Color(0xFF87A6C1),
        accent = Color(0xFF22D3EE),
        onAccent = Color(0xFF042A34),
        accentHover = Color(0xFF67E8F9),
        accentContainer = Color(0xFF0D3A4B),
        onAccentContainer = Color(0xFF7DE3F4),
        workspaceBackground = Color(0xFF0D2235),
        workspaceHeader = Color(0xFF122A40),
        workspacePanel = Color(0xFF0D2235),
        workspaceCanvas = Color(0xFF061424),
        navigationBackground = Color(0xFF04101C),
        navigationBorder = Color(0xFF1D405C),
        navigationHover = Color(0xFF0A2033),
        navigationSelected = Color(0xFF0B2C3B),
        onNavigation = Color(0xFFDCEAF6),
        onNavigationMuted = Color(0xFF87A6C1),
        success = Color(0xFF34D399),
        onSuccess = Color(0xFF04101C),
        successContainer = Color(0xFF0A3329),
        onSuccessContainer = Color(0xFF6EE7B7),
        warning = Color(0xFFFBBF24),
        onWarning = Color(0xFF04101C),
        warningContainer = Color(0xFF35290B),
        onWarningContainer = Color(0xFFFCD34D),
        info = Color(0xFFA5C4DC),
        onInfo = Color(0xFF04101C),
        infoContainer = Color(0xFF12293C),
        onInfoContainer = Color(0xFFA5C4DC),
        uq = Color(0xFFC4B5FD),
        onUq = Color(0xFF04101C),
        uqContainer = Color(0xFF241C46),
        onUqContainer = Color(0xFFC4B5FD),
        error = Color(0xFFFB7185),
        onError = Color(0xFF04101C),
        errorContainer = Color(0xFF3B1520),
        onErrorContainer = Color(0xFFFDA4AF),
        scrim = Color(0xB3020A12),
        series =
            listOf(
                Color(0xFF22D3EE),
                Color(0xFF60A5FA),
                Color(0xFFA78BFA),
                Color(0xFF2DD4BF),
                Color(0xFFFBBF24),
                Color(0xFFFB7185),
                Color(0xFFA3E635),
                Color(0xFF94A3B8),
            ),
    )

private val OxideLight =
    ThemePaletteSpec(
        background = Color(0xFFF7F4F0),
        surface = Color.White,
        containerLowest = Color.White,
        containerLow = Color(0xFFFAF8F5),
        container = Color(0xFFF0ECE7),
        containerHigh = Color(0xFFE8E2DB),
        containerHighest = Color(0xFFDDD5CC),
        outline = Color(0xFFC9C0B6),
        outlineVariant = Color(0xFFE5DFD8),
        onSurface = Color(0xFF1C1917),
        onSurfaceVariant = Color(0xFF6B625A),
        accent = Color(0xFFC2410C),
        onAccent = Color.White,
        accentHover = Color(0xFF9A3412),
        accentContainer = Color(0xFFFBEADF),
        onAccentContainer = Color(0xFF8A2F0B),
        workspaceBackground = Color(0xFFE7E1DA),
        workspaceHeader = Color(0xFFDCD4CB),
        workspacePanel = Color(0xFFE7E1DA),
        workspaceCanvas = Color(0xFFF7F4F0),
        navigationBackground = Color(0xFF211C18),
        navigationBorder = Color(0xFF4B4036),
        navigationHover = Color(0xFF2D2620),
        navigationSelected = Color(0xFF33251D),
        onNavigation = Color(0xFFF3EEE8),
        onNavigationMuted = Color(0xFFB8AAA0),
        success = Color(0xFF15803D),
        onSuccess = Color.White,
        successContainer = Color(0xFFE4F1E4),
        onSuccessContainer = Color(0xFF14532D),
        warning = Color(0xFFA16207),
        onWarning = Color.White,
        warningContainer = Color(0xFFF8F0D4),
        onWarningContainer = Color(0xFF854D0E),
        info = Color(0xFF0F766E),
        onInfo = Color.White,
        infoContainer = Color(0xFFE0EEEC),
        onInfoContainer = Color(0xFF115E59),
        uq = Color(0xFF7E22CE),
        onUq = Color.White,
        uqContainer = Color(0xFFF1E7F9),
        onUqContainer = Color(0xFF6B21A8),
        error = Color(0xFFBE123C),
        onError = Color.White,
        errorContainer = Color(0xFFFAE4E8),
        onErrorContainer = Color(0xFF9F1239),
        scrim = Color(0x731C1917),
        series =
            listOf(
                Color(0xFFC2410C),
                Color(0xFF0F766E),
                Color(0xFFA16207),
                Color(0xFFBE123C),
                Color(0xFF1D4ED8),
                Color(0xFF15803D),
                Color(0xFF7E22CE),
                Color(0xFF78716C),
            ),
    )

private val OxideDark =
    ThemePaletteSpec(
        background = Color(0xFF0C0A09),
        surface = Color(0xFF16130F),
        containerLowest = Color(0xFF080706),
        containerLow = Color(0xFF110F0C),
        container = Color(0xFF1E1A16),
        containerHigh = Color(0xFF29231D),
        containerHighest = Color(0xFF352D25),
        outline = Color(0xFF443C33),
        outlineVariant = Color(0xFF2B251F),
        onSurface = Color(0xFFF5F1EC),
        onSurfaceVariant = Color(0xFFA8A29A),
        accent = Color(0xFFFB923C),
        onAccent = Color(0xFF1C1917),
        accentHover = Color(0xFFFDBA74),
        accentContainer = Color(0xFF3A2214),
        onAccentContainer = Color(0xFFFDBA74),
        workspaceBackground = Color(0xFF1E1A16),
        workspaceHeader = Color(0xFF29231D),
        workspacePanel = Color(0xFF1E1A16),
        workspaceCanvas = Color(0xFF0C0A09),
        navigationBackground = Color(0xFF080706),
        navigationBorder = Color(0xFF3B332B),
        navigationHover = Color(0xFF181410),
        navigationSelected = Color(0xFF2D1E14),
        onNavigation = Color(0xFFF5F1EC),
        onNavigationMuted = Color(0xFFA8A29A),
        success = Color(0xFF4ADE80),
        onSuccess = Color(0xFF0C0A09),
        successContainer = Color(0xFF15301D),
        onSuccessContainer = Color(0xFF86EFAC),
        warning = Color(0xFFFACC15),
        onWarning = Color(0xFF0C0A09),
        warningContainer = Color(0xFF332A08),
        onWarningContainer = Color(0xFFFDE047),
        info = Color(0xFF5EEAD4),
        onInfo = Color(0xFF0C0A09),
        infoContainer = Color(0xFF10302C),
        onInfoContainer = Color(0xFF99F6E4),
        uq = Color(0xFFD8B4FE),
        onUq = Color(0xFF0C0A09),
        uqContainer = Color(0xFF2D1B3D),
        onUqContainer = Color(0xFFD8B4FE),
        error = Color(0xFFFB7185),
        onError = Color(0xFF0C0A09),
        errorContainer = Color(0xFF3A141F),
        onErrorContainer = Color(0xFFFDA4AF),
        scrim = Color(0xB3000000),
        series =
            listOf(
                Color(0xFFFB923C),
                Color(0xFF5EEAD4),
                Color(0xFFFACC15),
                Color(0xFFFB7185),
                Color(0xFF93C5FD),
                Color(0xFF86EFAC),
                Color(0xFFD8B4FE),
                Color(0xFFD6D3D1),
            ),
    )

private val CommandVioletLight =
    ThemePaletteSpec(
        background = Color(0xFFF8F8FA),
        surface = Color.White,
        containerLowest = Color.White,
        containerLow = Color(0xFFF7F7F9),
        container = Color(0xFFEDEEF2),
        containerHigh = Color(0xFFE4E5EB),
        containerHighest = Color(0xFFDADCE4),
        outline = Color(0xFFBABECB),
        outlineVariant = Color(0xFFDCDEE6),
        onSurface = Color(0xFF1B1B24),
        onSurfaceVariant = Color(0xFF626475),
        accent = Color(0xFF6D35C5),
        onAccent = Color.White,
        accentHover = Color(0xFF5726A6),
        accentContainer = Color(0xFFF0E8FC),
        onAccentContainer = Color(0xFF52219C),
        workspaceBackground = Color(0xFFE6E7EC),
        workspaceHeader = Color(0xFFDCDDE5),
        workspacePanel = Color(0xFFE6E7EC),
        workspaceCanvas = Color(0xFFF8F8FA),
        navigationBackground = Color(0xFF1C1D29),
        navigationBorder = Color(0xFF3E4052),
        navigationHover = Color(0xFF282A38),
        navigationSelected = Color(0xFF30283F),
        onNavigation = Color(0xFFF0F0F5),
        onNavigationMuted = Color(0xFFA8A9B8),
        success = Color(0xFF047857),
        onSuccess = Color.White,
        successContainer = Color(0xFFECFDF5),
        onSuccessContainer = Color(0xFF047857),
        warning = Color(0xFFB45309),
        onWarning = Color.White,
        warningContainer = Color(0xFFFFFBEB),
        onWarningContainer = Color(0xFF92400E),
        info = Color(0xFF526273),
        onInfo = Color.White,
        infoContainer = Color(0xFFEDF1F5),
        onInfoContainer = Color(0xFF354454),
        uq = Color(0xFF6D35C5),
        onUq = Color.White,
        uqContainer = Color(0xFFF0E8FC),
        onUqContainer = Color(0xFF52219C),
        error = Color(0xFFDC2626),
        onError = Color.White,
        errorContainer = Color(0xFFFEF2F2),
        onErrorContainer = Color(0xFFB91C1C),
        scrim = Color(0x66000000),
        series =
            listOf(
                Color(0xFF6D35C5),
                Color(0xFF0F766E),
                Color(0xFFB45309),
                Color(0xFF2563A8),
                Color(0xFFBE123C),
                Color(0xFF527A22),
                Color(0xFF9A3D75),
                Color(0xFF596275),
            ),
    )

private val CommandVioletDark =
    ThemePaletteSpec(
        background = Color(0xFF10111A),
        surface = Color(0xFF171823),
        containerLowest = Color(0xFF0C0D14),
        containerLow = Color(0xFF14151F),
        container = Color(0xFF1E202C),
        containerHigh = Color(0xFF272936),
        containerHighest = Color(0xFF313442),
        outline = Color(0xFF414455),
        outlineVariant = Color(0xFF2C2E3C),
        onSurface = Color(0xFFF0F0F5),
        onSurfaceVariant = Color(0xFFA2A4B4),
        accent = Color(0xFFA78BFA),
        onAccent = Color(0xFF1B1230),
        accentHover = Color(0xFFC4B5FD),
        accentContainer = Color(0xFF332653),
        onAccentContainer = Color(0xFFD8CCFF),
        workspaceBackground = Color(0xFF1E202C),
        workspaceHeader = Color(0xFF272936),
        workspacePanel = Color(0xFF1E202C),
        workspaceCanvas = Color(0xFF10111A),
        navigationBackground = Color(0xFF0C0D14),
        navigationBorder = Color(0xFF363847),
        navigationHover = Color(0xFF181A24),
        navigationSelected = Color(0xFF2B2340),
        onNavigation = Color(0xFFF0F0F5),
        onNavigationMuted = Color(0xFF9698A8),
        success = Color(0xFF34D399),
        onSuccess = Color(0xFF0C0D14),
        successContainer = Color(0xFF0A2818),
        onSuccessContainer = Color(0xFF6EE7B7),
        warning = Color(0xFFFCD34D),
        onWarning = Color(0xFF0C0D14),
        warningContainer = Color(0xFF2A1F0A),
        onWarningContainer = Color(0xFFFDE68A),
        info = Color(0xFFCBD5E1),
        onInfo = Color(0xFF0C0D14),
        infoContainer = Color(0xFF222636),
        onInfoContainer = Color(0xFFCBD5E1),
        uq = Color(0xFFC4B5FD),
        onUq = Color(0xFF0C0D14),
        uqContainer = Color(0xFF332653),
        onUqContainer = Color(0xFFD8CCFF),
        error = Color(0xFFF87171),
        onError = Color(0xFF0C0D14),
        errorContainer = Color(0xFF2A1414),
        onErrorContainer = Color(0xFFFCA5A5),
        scrim = Color(0x99000000),
        series =
            listOf(
                Color(0xFFA78BFA),
                Color(0xFF2DD4BF),
                Color(0xFFFCD34D),
                Color(0xFF7DD3FC),
                Color(0xFFFB7185),
                Color(0xFFA3E635),
                Color(0xFFF0A6CA),
                Color(0xFFB8BAC7),
            ),
    )
